# Generated by Django 3.0.7 on 2020-06-11 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20200611_1914'),
        ('company', '0002_vacancy_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='elective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Elective'),
        ),
    ]
