# Generated by Django 3.0.7 on 2020-06-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20200611_1914'),
        ('company', '0007_auto_20200614_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Student')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Vacancy')),
            ],
        ),
    ]
