# Generated by Django 3.0.7 on 2020-06-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSkils',
            new_name='StudentSkills',
        ),
        migrations.AddField(
            model_name='elective',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.Speciality'),
        ),
    ]
